

highlight_field_list = (\
    'accessToSources'\
	, 'actionsToMinimizeLoss'\
	, 'affiliation_ss'\
	, 'astroFacility'\
	, 'astroInstrument'\
	, 'astroObject'\
	, 'astroType'\
	, 'author'\
	, 'authorAffiliation'\
	, 'authorIdentifier'\
	, 'authorIdentifierScheme'\
	, 'authorName'\
	, 'characteristicOfSources'\
	, 'city'\
	, 'cleaningOperations'\
	, 'collectionMode'\
	, 'collectorTraining'\
	, 'contributor'\
	, 'contributorName'\
	, 'contributorType'\
	, 'controlOperations'\
	, 'country'\
	, 'coverage.Depth'\
	, 'coverage.ObjectCount'\
	, 'coverage.ObjectDensity'\
	, 'coverage.Polarization'\
	, 'coverage.Redshift.MaximumValue'\
	, 'coverage.Redshift.MinimumValue'\
	, 'coverage.RedshiftValue'\
	, 'coverage.SkyFraction'\
	, 'coverage.Spatial'\
	, 'coverage.Spectral.Bandpass'\
	, 'coverage.Spectral.CentralWavelength'\
	, 'coverage.Spectral.MaximumWavelength'\
	, 'coverage.Spectral.MinimumWavelength'\
	, 'coverage.Spectral.Wavelength'\
	, 'coverage.Temporal'\
	, 'coverage.Temporal.StartTime'\
	, 'coverage.Temporal.StopTime'\
	, 'dataCollectionSituation'\
	, 'dataCollector'\
	, 'dataSources'\
	, 'datasetContact'\
	, 'datasetLevelErrorNotes'\
	, 'dateOfCollection'\
	, 'dateOfCollectionEnd'\
	, 'dateOfCollectionStart'\
	, 'dateOfDeposit'\
	, 'depositor'\
	, 'description'\
	, 'deviationsFromSampleDesign'\
	, 'distributor'\
	, 'distributorAbbreviation'\
	, 'distributorAffiliation'\
	, 'distributorName'\
	, 'dsDescription'\
	, 'eastLongitude'\
	, 'filename_without_extension_en'\
	, 'filetype_en'\
	, 'filetypemime_s'\
	, 'frequencyOfDataCollection'\
	, 'geographicBoundingBox'\
	, 'geographicCoverage' # last\
	, 'geographicUnit'\
	, 'grantNumber'\
	, 'grantNumberAgency'\
	, 'grantNumberValue'\
	, 'keyword'\
	, 'kindOfData'\
	, 'language'\
	, 'name'\
	, 'northLongitude'\
	, 'notesText'\
	, 'originOfSources'\
	, 'otherDataAppraisal'\
	#, 'otherGeographicCoverage'\
	, 'otherId'\
	, 'otherIdAgency'\
	, 'otherIdValue'\
    , 'otherReferences'\
	, 'producer'\
	, 'producerAbbreviation'\
	, 'producerAffiliation'\
	, 'producerName'\
	, 'productionDate'\
	, 'productionPlace'\
	, 'publication'\
	, 'publicationCitation'\
	, 'publicationIDNumber'\
	, 'publicationIDType'\
	, 'publicationURL'\
	, 'redshiftType'\
	, 'relatedDatasets'\
	, 'relatedMaterial'\
	, 'researchInstrument'\
	, 'resolution.Redshift'\
	, 'resolution.Spatial'\
	, 'resolution.Spectral'\
	, 'resolution.Temporal'\
	, 'responseRate'\
	, 'sampleFrame'\
	, 'samplingErrorEstimates'\
	, 'samplingProcedure'\
	, 'series'\
	, 'seriesInformation'\
	, 'seriesName'\
	, 'software'\
	, 'softwareName'\
	, 'softwareVersion'\
	, 'southLongitude'\
	, 'state'\
	, 'studyAssayCellType'\
	, 'studyAssayMeasurementType'\
	, 'studyAssayOrganism'\
	, 'studyDesignType'\
	, 'studyFactorType'\
	, 'subject'\
	, 'targetSampleSize'\
	, 'timeMethod'\
	, 'timePeriodCovered'\
	, 'timePeriodCoveredEnd'\
	, 'timePeriodCoveredStart'\
	, 'title'\
	, 'topicClassValue'\
	, 'topicClassVocab'\
	, 'topicClassVocabURI'\
	, 'topicClassification'\
	, 'unitOfAnalysis'\
	, 'universe'\
	, 'variable_label_en'\
	, 'variable_name_en'\
	, 'weighting'\
	, 'westLongitude'\
)

