#!/bin/sh
# This script should be wrapped by another script that
# encloses all of these commands in "scl enable python27"
# and is run by the "plaid" user for periodic builds
# i.e. scl enable python27 "path/to/this/script.sh"
# See also http://developerblog.redhat.com/2013/02/14/setting-up-django-and-python-2-7-on-red-hat-enterprise-6-the-easy-way/
#source /usr/bin/virtualenvwrapper.sh # python 2.6 version
source /opt/rh/python27/root/usr/bin/virtualenvwrapper.sh
#
# Setup virtualenv
echo "Setup virtualenv"
export WORKON_HOME=/webapps/virtualenvs
workon dataverse_org
#
# Validate settings file
#
echo "Validate settings file"
cd /webapps/code/dataverse.org/dataverse_org
python manage.py validate --settings=dataverse_org.settings.production
#
# Create sqlite database + initial tables
#
echo "Create sqlite database + initial tables"
python manage.py syncdb --noinput --settings=dataverse_org.settings.production
#

#
echo "Run collectstatic to copy files to the static www directory"
#
python manage.py collectstatic --noinput --settings=dataverse_org.settings.production

#
echo "Load federated dataverses from fixtures"
#
echo "Copy federated dataverse logo files to web path"
cp /webapps/code/dataverse.org/dataverse_org/media/federated_logos/* /var/www/dataverse_org/media/federated_logos

echo "Load federated dataverses from fixtures"
python manage.py loaddata apps/federated_dataverses/fixtures/initial_data.json --settings=dataverse_org.settings.production

#
echo "Save flatpages to back up directory"
#
python manage.py dumpdata flatpages --indent=4 --settings=dataverse_org.settings.production > /webapps/data/dataverse_org/backups/flatpages.json
sudo -u datascience /webapps/code/dataverse.org/deploy/backup

# FIXME touch to restart Apache (WSGIScriptReloading On)
sudo /sbin/service httpd restart
